import { DomainId } from "@/modules/types";

export type ComponentCategory =
  | "microcontroller"
  | "microcomputer"
  | "sensor"
  | "actuator"
  | "power"
  | "passive"
  | "communication"
  | "robotics"
  | "aerospace"
  | "energy"
  | "industrial";

export type CatalogComponent = {
  sku: string;
  componentType: string;
  name: string;
  vendor: string;
  category: ComponentCategory;
  domain: DomainId;
  protocols: string[];
  packageType: string;
  simulationLevel: "interactive" | "engineering" | "hil-ready";
  firmwareProfileId?: string;
  tags: string[];
  notes: string;
};

export const marketComponentCatalog: CatalogComponent[] = [
  {
    sku: "arduino-uno-r3",
    componentType: "arduino-uno",
    name: "Arduino Uno R3",
    vendor: "Arduino",
    category: "microcontroller",
    domain: "embedded",
    protocols: ["GPIO", "PWM", "UART", "I2C", "SPI"],
    packageType: "development-board",
    simulationLevel: "interactive",
    firmwareProfileId: "fw.arduino.uno",
    tags: ["student", "atmega328p", "controls", "electronics"],
    notes: "Baseline board for mechatronics, instrumentation, and control labs.",
  },
  {
    sku: "arduino-mega-2560",
    componentType: "arduino-mega",
    name: "Arduino Mega 2560",
    vendor: "Arduino",
    category: "microcontroller",
    domain: "embedded",
    protocols: ["GPIO", "PWM", "UART", "I2C", "SPI"],
    packageType: "development-board",
    simulationLevel: "engineering",
    firmwareProfileId: "fw.arduino.mega",
    tags: ["automation", "fixtures", "multi-io", "motion"],
    notes: "High pin-count AVR target for automation rigs and lab fixtures.",
  },
  {
    sku: "arduino-nano",
    componentType: "arduino-nano",
    name: "Arduino Nano",
    vendor: "Arduino",
    category: "microcontroller",
    domain: "embedded",
    protocols: ["GPIO", "PWM", "UART", "I2C", "SPI"],
    packageType: "development-board",
    simulationLevel: "interactive",
    firmwareProfileId: "fw.arduino.nano",
    tags: ["compact", "breadboard", "portable"],
    notes: "Compact AVR controller frequently used in embedded prototyping.",
  },
  {
    sku: "esp32-wroom-32",
    componentType: "esp32-wroom",
    name: "ESP32-WROOM-32",
    vendor: "Espressif",
    category: "microcontroller",
    domain: "iot",
    protocols: ["GPIO", "PWM", "UART", "I2C", "SPI", "Wi-Fi", "Bluetooth"],
    packageType: "module",
    simulationLevel: "engineering",
    firmwareProfileId: "fw.esp32.edge",
    tags: ["iot", "wifi", "mqtt", "edge"],
    notes: "Wireless MCU for connected devices, gateways, and telemetry nodes.",
  },
  {
    sku: "esp8266-nodemcu",
    componentType: "esp8266-nodemcu",
    name: "ESP8266 NodeMCU",
    vendor: "Espressif",
    category: "microcontroller",
    domain: "iot",
    protocols: ["GPIO", "PWM", "UART", "I2C", "SPI", "Wi-Fi"],
    packageType: "development-board",
    simulationLevel: "interactive",
    firmwareProfileId: "fw.esp8266.edge",
    tags: ["wifi", "telemetry", "smart-home"],
    notes: "Low-cost wireless board for home automation and sensor telemetry.",
  },
  {
    sku: "stm32f103c8t6",
    componentType: "stm32f103",
    name: "STM32F103C8T6 Blue Pill",
    vendor: "STMicroelectronics",
    category: "microcontroller",
    domain: "embedded",
    protocols: ["GPIO", "PWM", "UART", "I2C", "SPI", "CAN"],
    packageType: "development-board",
    simulationLevel: "engineering",
    firmwareProfileId: "fw.stm32.motion",
    tags: ["motor-control", "realtime", "controls", "hal"],
    notes: "ARM Cortex-M control board for motion and industrial control loops.",
  },
  {
    sku: "rp2040-pico",
    componentType: "raspberry-pi-pico",
    name: "Raspberry Pi Pico",
    vendor: "Raspberry Pi",
    category: "microcontroller",
    domain: "embedded",
    protocols: ["GPIO", "PWM", "UART", "I2C", "SPI", "PIO"],
    packageType: "development-board",
    simulationLevel: "engineering",
    firmwareProfileId: "fw.rp2040.pio",
    tags: ["pio", "timing", "signal-processing", "instrumentation"],
    notes: "PIO-capable controller for precise timing and interface emulation.",
  },
  {
    sku: "attiny85",
    componentType: "attiny85",
    name: "ATtiny85 Development Target",
    vendor: "Microchip",
    category: "microcontroller",
    domain: "embedded",
    protocols: ["GPIO", "PWM", "ADC"],
    packageType: "mcu-target",
    simulationLevel: "interactive",
    firmwareProfileId: "fw.attiny.lowpower",
    tags: ["low-power", "tinyml", "ultra-low-cost"],
    notes: "Ultra-small MCU target for compact and low-power embedded controls.",
  },
  {
    sku: "raspberry-pi-4b",
    componentType: "raspberry-pi-4b",
    name: "Raspberry Pi 4B",
    vendor: "Raspberry Pi",
    category: "microcomputer",
    domain: "embedded",
    protocols: ["GPIO", "UART", "I2C", "SPI", "Ethernet", "Wi-Fi"],
    packageType: "single-board-computer",
    simulationLevel: "engineering",
    firmwareProfileId: "fw.rpi.gateway",
    tags: ["linux", "gateway", "ros2", "edge-service"],
    notes: "Linux SBC for gateways, robotics brains, and industrial data collection.",
  },
  {
    sku: "jetson-orin-nano",
    componentType: "jetson-nano",
    name: "Jetson Orin Nano",
    vendor: "NVIDIA",
    category: "microcomputer",
    domain: "robotics",
    protocols: ["GPIO", "UART", "I2C", "SPI", "Ethernet", "CSI"],
    packageType: "ai-compute-module",
    simulationLevel: "hil-ready",
    firmwareProfileId: "fw.jetson.autonomy",
    tags: ["ai", "perception", "robotics", "cuda"],
    notes: "Edge AI target for perception-heavy autonomy and multi-sensor fusion.",
  },
  {
    sku: "beaglebone-black",
    componentType: "beaglebone-black",
    name: "BeagleBone Black",
    vendor: "BeagleBoard.org",
    category: "microcomputer",
    domain: "industrial",
    protocols: ["GPIO", "UART", "I2C", "SPI", "Ethernet", "PRU"],
    packageType: "single-board-computer",
    simulationLevel: "engineering",
    firmwareProfileId: "fw.beaglebone.pru",
    tags: ["pru", "industrial", "realtime-io"],
    notes: "Industrial SBC with PRU co-processors for real-time interfacing.",
  },
  {
    sku: "hc-sr04",
    componentType: "hc-sr04",
    name: "HC-SR04 Ultrasonic Sensor",
    vendor: "Generic",
    category: "sensor",
    domain: "embedded",
    protocols: ["GPIO"],
    packageType: "sensor-module",
    simulationLevel: "interactive",
    tags: ["distance", "robotics", "avoidance"],
    notes: "Distance sensor for obstacle avoidance, tank level, and classroom robotics.",
  },
  {
    sku: "dht22-am2302",
    componentType: "dht22",
    name: "DHT22 / AM2302",
    vendor: "Aosong",
    category: "sensor",
    domain: "iot",
    protocols: ["Single-wire"],
    packageType: "sensor-module",
    simulationLevel: "interactive",
    tags: ["environment", "humidity", "temperature"],
    notes: "Environmental telemetry sensor for climate, storage, and agriculture models.",
  },
  {
    sku: "bmp280",
    componentType: "bmp280",
    name: "BMP280 Barometric Sensor",
    vendor: "Bosch",
    category: "sensor",
    domain: "aerospace",
    protocols: ["I2C", "SPI"],
    packageType: "sensor-module",
    simulationLevel: "engineering",
    tags: ["altitude", "barometer", "uav"],
    notes: "Pressure and altitude estimation source for drones and environmental systems.",
  },
  {
    sku: "bme280",
    componentType: "bmp280",
    name: "BME280",
    vendor: "Bosch",
    category: "sensor",
    domain: "iot",
    protocols: ["I2C", "SPI"],
    packageType: "sensor-module",
    simulationLevel: "engineering",
    tags: ["pressure", "humidity", "weather"],
    notes: "Pressure, humidity, and temperature sensor for environmental telemetry.",
  },
  {
    sku: "mpu6050",
    componentType: "mpu6050",
    name: "MPU-6050 IMU",
    vendor: "TDK InvenSense",
    category: "sensor",
    domain: "robotics",
    protocols: ["I2C"],
    packageType: "sensor-module",
    simulationLevel: "engineering",
    tags: ["imu", "navigation", "balance", "fusion"],
    notes: "6-axis inertial measurement source for balancing and navigation systems.",
  },
  {
    sku: "gps-neo6m",
    componentType: "gps-neo6m",
    name: "NEO-6M GPS Module",
    vendor: "u-blox",
    category: "sensor",
    domain: "aerospace",
    protocols: ["UART"],
    packageType: "sensor-module",
    simulationLevel: "engineering",
    tags: ["gps", "navigation", "uav", "field-robotics"],
    notes: "Navigation-grade position source for aerial and field systems.",
  },
  {
    sku: "ina219",
    componentType: "ina219-current",
    name: "INA219 Current Sensor",
    vendor: "Texas Instruments",
    category: "sensor",
    domain: "energy",
    protocols: ["I2C"],
    packageType: "power-monitor",
    simulationLevel: "engineering",
    tags: ["current", "power", "bus-voltage"],
    notes: "Current and bus voltage telemetry for power electronics and battery systems.",
  },
  {
    sku: "soil-moisture-capacitive",
    componentType: "soil-moisture",
    name: "Capacitive Soil Moisture Sensor",
    vendor: "Generic",
    category: "sensor",
    domain: "iot",
    protocols: ["ADC"],
    packageType: "sensor-probe",
    simulationLevel: "interactive",
    tags: ["agriculture", "watering", "greenhouse"],
    notes: "Low-cost plant and greenhouse telemetry source.",
  },
  {
    sku: "water-level-vertical",
    componentType: "water-level",
    name: "Water Level Sensor",
    vendor: "Generic",
    category: "sensor",
    domain: "industrial",
    protocols: ["ADC"],
    packageType: "sensor-probe",
    simulationLevel: "interactive",
    tags: ["tank", "infrastructure", "water"],
    notes: "Fluid level sensor for process and utility systems.",
  },
  {
    sku: "pir-hc-sr501",
    componentType: "pir-sensor",
    name: "HC-SR501 PIR Motion Sensor",
    vendor: "Generic",
    category: "sensor",
    domain: "iot",
    protocols: ["GPIO"],
    packageType: "sensor-module",
    simulationLevel: "interactive",
    tags: ["occupancy", "security", "automation"],
    notes: "Motion sensor for building automation and security workflows.",
  },
  {
    sku: "mq2-gas",
    componentType: "mq2-gas",
    name: "MQ-2 Gas Sensor",
    vendor: "Winsen",
    category: "sensor",
    domain: "industrial",
    protocols: ["ADC"],
    packageType: "sensor-module",
    simulationLevel: "interactive",
    tags: ["gas", "safety", "air-quality"],
    notes: "Combustible gas sensor for safety monitoring and alerting logic.",
  },
  {
    sku: "color-tcs3200",
    componentType: "color-sensor-tcs3200",
    name: "TCS3200 Color Sensor",
    vendor: "AMS",
    category: "sensor",
    domain: "industrial",
    protocols: ["GPIO"],
    packageType: "sensor-module",
    simulationLevel: "engineering",
    tags: ["sorting", "quality-control", "vision-lite"],
    notes: "Color sensing module for sorting, QA, and conveyor workflows.",
  },
  {
    sku: "lidar-lite-v3",
    componentType: "lidar-lite",
    name: "LIDAR-Lite v3",
    vendor: "Garmin",
    category: "sensor",
    domain: "robotics",
    protocols: ["I2C", "PWM"],
    packageType: "sensor-module",
    simulationLevel: "engineering",
    tags: ["range", "mapping", "autonomy"],
    notes: "Compact rangefinding sensor for robotics and field autonomy.",
  },
  {
    sku: "servo-sg90",
    componentType: "servo-sg90",
    name: "SG90 Micro Servo",
    vendor: "TowerPro",
    category: "actuator",
    domain: "robotics",
    protocols: ["PWM"],
    packageType: "servo",
    simulationLevel: "interactive",
    tags: ["student", "servo", "position"],
    notes: "Low-cost positional actuator for classroom robotics and fixtures.",
  },
  {
    sku: "servo-mg996r",
    componentType: "servo-mg996r",
    name: "MG996R Servo",
    vendor: "TowerPro",
    category: "actuator",
    domain: "robotics",
    protocols: ["PWM"],
    packageType: "servo",
    simulationLevel: "engineering",
    tags: ["torque", "manipulator", "position"],
    notes: "Higher torque servo for manipulators and heavier linkages.",
  },
  {
    sku: "nema17",
    componentType: "nema17-stepper",
    name: "NEMA 17 Stepper",
    vendor: "Generic",
    category: "actuator",
    domain: "industrial",
    protocols: ["STEP/DIR"],
    packageType: "motor",
    simulationLevel: "engineering",
    tags: ["cnc", "motion", "automation"],
    notes: "Stepper motor used in CNC, 3D printing, and automation systems.",
  },
  {
    sku: "l298n-driver",
    componentType: "l298n-driver",
    name: "L298N Dual H-Bridge",
    vendor: "STMicroelectronics",
    category: "actuator",
    domain: "embedded",
    protocols: ["GPIO", "PWM"],
    packageType: "motor-driver",
    simulationLevel: "interactive",
    tags: ["motor-driver", "student", "h-bridge"],
    notes: "Legacy H-bridge driver still common in entry robotics labs.",
  },
  {
    sku: "a4988",
    componentType: "a4988-driver",
    name: "A4988 Stepper Driver",
    vendor: "Allegro",
    category: "actuator",
    domain: "industrial",
    protocols: ["STEP/DIR"],
    packageType: "driver-module",
    simulationLevel: "engineering",
    tags: ["stepper", "cnc", "motion-control"],
    notes: "Compact driver for precision stepper systems.",
  },
  {
    sku: "dc-motor-6v",
    componentType: "dc-motor",
    name: "6V Brushed DC Motor",
    vendor: "Generic",
    category: "actuator",
    domain: "robotics",
    protocols: ["DC"],
    packageType: "motor",
    simulationLevel: "interactive",
    tags: ["traction", "drive", "student-robotics"],
    notes: "Brushed motor for drive trains, feeders, and small mechanisms.",
  },
  {
    sku: "linear-actuator-100mm",
    componentType: "linear-actuator",
    name: "100 mm Linear Actuator",
    vendor: "Generic",
    category: "actuator",
    domain: "industrial",
    protocols: ["DC", "Limit-switch"],
    packageType: "actuator",
    simulationLevel: "engineering",
    tags: ["linear-motion", "automation", "jigs"],
    notes: "Linear motion element for clamps, feeders, and lab fixtures.",
  },
  {
    sku: "solenoid-valve-12v",
    componentType: "solenoid-valve",
    name: "12V Solenoid Valve",
    vendor: "Generic",
    category: "actuator",
    domain: "industrial",
    protocols: ["DC"],
    packageType: "fluid-actuator",
    simulationLevel: "engineering",
    tags: ["fluid", "valve", "process-control"],
    notes: "Fluid-control actuator for pneumatic and process workflows.",
  },
  {
    sku: "led-5mm-red",
    componentType: "led",
    name: "5 mm Red LED",
    vendor: "Generic",
    category: "passive",
    domain: "embedded",
    protocols: ["DC"],
    packageType: "through-hole",
    simulationLevel: "interactive",
    tags: ["indicator", "student", "visual-output"],
    notes: "Basic indicator output for digital logic and test benches.",
  },
  {
    sku: "resistor-220-ohm",
    componentType: "resistor",
    name: "220 Ohm Resistor",
    vendor: "Generic",
    category: "passive",
    domain: "embedded",
    protocols: ["analog"],
    packageType: "through-hole",
    simulationLevel: "interactive",
    tags: ["passive", "current-limiting", "student"],
    notes: "Common current-limiting element for LEDs and signal conditioning.",
  },
  {
    sku: "capacitor-10uf",
    componentType: "capacitor",
    name: "10 uF Capacitor",
    vendor: "Generic",
    category: "passive",
    domain: "embedded",
    protocols: ["analog"],
    packageType: "through-hole",
    simulationLevel: "interactive",
    tags: ["filtering", "decoupling", "power"],
    notes: "Basic energy storage and filtering element.",
  },
  {
    sku: "diode-1n4007",
    componentType: "diode",
    name: "1N4007 Diode",
    vendor: "Vishay",
    category: "passive",
    domain: "energy",
    protocols: ["analog"],
    packageType: "through-hole",
    simulationLevel: "engineering",
    tags: ["rectifier", "reverse-protection", "power"],
    notes: "Rectification and reverse-polarity protection element.",
  },
  {
    sku: "mosfet-irf540n",
    componentType: "mosfet-irf540",
    name: "IRF540N MOSFET",
    vendor: "Infineon",
    category: "power",
    domain: "energy",
    protocols: ["gate-drive"],
    packageType: "to-220",
    simulationLevel: "engineering",
    tags: ["switching", "power-stage", "dc-drive"],
    notes: "Power switching device for motor, lighting, and power-stage experiments.",
  },
  {
    sku: "relay-1ch-5v",
    componentType: "relay-module",
    name: "1-Channel Relay Module",
    vendor: "Songle",
    category: "power",
    domain: "industrial",
    protocols: ["GPIO"],
    packageType: "relay-module",
    simulationLevel: "engineering",
    tags: ["isolation", "switching", "automation"],
    notes: "Isolated switching module for building and process control.",
  },
  {
    sku: "oled-ssd1306",
    componentType: "oled-ssd1306",
    name: "SSD1306 OLED",
    vendor: "Generic",
    category: "communication",
    domain: "embedded",
    protocols: ["I2C"],
    packageType: "display-module",
    simulationLevel: "interactive",
    tags: ["display", "ui", "telemetry"],
    notes: "Compact local display for diagnostics and instrumentation.",
  },
  {
    sku: "rfid-rc522",
    componentType: "rfid-rc522",
    name: "RC522 RFID Reader",
    vendor: "NXP",
    category: "communication",
    domain: "iot",
    protocols: ["SPI"],
    packageType: "communication-module",
    simulationLevel: "engineering",
    tags: ["access-control", "asset-tracking", "rfid"],
    notes: "RFID access, identity, and asset interaction module.",
  },
  {
    sku: "nrf24l01",
    componentType: "nrf24l01",
    name: "nRF24L01",
    vendor: "Nordic Semiconductor",
    category: "communication",
    domain: "iot",
    protocols: ["SPI", "2.4GHz"],
    packageType: "wireless-module",
    simulationLevel: "engineering",
    tags: ["wireless", "mesh", "short-range"],
    notes: "Low-power short-range radio for distributed device meshes.",
  },
  {
    sku: "can-mcp2515",
    componentType: "can-bus-mcp2515",
    name: "MCP2515 CAN Module",
    vendor: "Microchip",
    category: "communication",
    domain: "industrial",
    protocols: ["CAN", "SPI"],
    packageType: "communication-module",
    simulationLevel: "engineering",
    firmwareProfileId: "fw.can.gateway",
    tags: ["can", "automotive", "industrial-bus"],
    notes: "CAN interface for vehicle and industrial network integration.",
  },
  {
    sku: "lora-sx1276",
    componentType: "lora-sx1276",
    name: "SX1276 LoRa Module",
    vendor: "Semtech",
    category: "communication",
    domain: "iot",
    protocols: ["SPI", "LoRa"],
    packageType: "wireless-module",
    simulationLevel: "engineering",
    tags: ["long-range", "iot", "telemetry"],
    notes: "Long-range telemetry radio for remote assets and outdoor systems.",
  },
  {
    sku: "lm7805",
    componentType: "lm7805",
    name: "LM7805 Regulator",
    vendor: "Texas Instruments",
    category: "power",
    domain: "energy",
    protocols: ["analog"],
    packageType: "to-220",
    simulationLevel: "interactive",
    tags: ["regulation", "power", "5v"],
    notes: "Linear regulator model for power rail design and dissipation studies.",
  },
  {
    sku: "lipo-3s",
    componentType: "lipo-battery",
    name: "3S LiPo Pack",
    vendor: "Generic",
    category: "power",
    domain: "energy",
    protocols: ["DC"],
    packageType: "battery-pack",
    simulationLevel: "engineering",
    tags: ["battery", "mobile-robotics", "uav"],
    notes: "Portable power source for drones, robots, and mobile instrumentation.",
  },
  {
    sku: "buck-converter-lm2596",
    componentType: "buck-converter",
    name: "LM2596 Buck Converter",
    vendor: "Texas Instruments",
    category: "power",
    domain: "energy",
    protocols: ["DC"],
    packageType: "power-module",
    simulationLevel: "engineering",
    tags: ["dc-dc", "efficiency", "power-rail"],
    notes: "DC conversion stage for embedded and robotics power rails.",
  },
  {
    sku: "tp4056-charger",
    componentType: "tp4056-charger",
    name: "TP4056 Charger Board",
    vendor: "NanJing Top Power",
    category: "power",
    domain: "energy",
    protocols: ["charging"],
    packageType: "charge-module",
    simulationLevel: "engineering",
    tags: ["charging", "battery-management", "consumer"],
    notes: "Li-ion charger module for portable energy systems.",
  },
  {
    sku: "solar-panel-50w",
    componentType: "solar-panel",
    name: "50W Solar Panel",
    vendor: "Generic",
    category: "energy",
    domain: "energy",
    protocols: ["DC"],
    packageType: "energy-source",
    simulationLevel: "engineering",
    tags: ["renewables", "off-grid", "pv"],
    notes: "Renewable source model for off-grid power and energy studies.",
  },
  {
    sku: "battery-bms-16s",
    componentType: "battery-bms-16s",
    name: "16S Battery Management System",
    vendor: "Generic",
    category: "energy",
    domain: "energy",
    protocols: ["CAN", "UART"],
    packageType: "bms-module",
    simulationLevel: "engineering",
    firmwareProfileId: "fw.bms.supervisor",
    tags: ["battery", "safety", "ev", "storage"],
    notes: "Battery pack supervision for EV and stationary storage simulations.",
  },
  {
    sku: "ur5e",
    componentType: "robot-arm-6dof",
    name: "UR5e Collaborative Arm",
    vendor: "Universal Robots",
    category: "robotics",
    domain: "robotics",
    protocols: ["Ethernet/IP", "ROS 2", "Fieldbus"],
    packageType: "industrial-robot",
    simulationLevel: "hil-ready",
    firmwareProfileId: "fw.ros2.manipulator",
    tags: ["cobot", "manipulator", "industrial"],
    notes: "Reference industrial manipulator for digital cell simulation.",
  },
  {
    sku: "quadcopter-450",
    componentType: "robot-quadcopter",
    name: "450-class Quadcopter",
    vendor: "Generic",
    category: "aerospace",
    domain: "aerospace",
    protocols: ["PWM", "MAVLink", "UART"],
    packageType: "uav-platform",
    simulationLevel: "engineering",
    firmwareProfileId: "fw.drone.autopilot",
    tags: ["uav", "flight-control", "mission"],
    notes: "UAV baseline for aerial robotics, mission rehearsal, and autonomy studies.",
  },
  {
    sku: "pixhawk-fc",
    componentType: "flight-controller-pixhawk",
    name: "Pixhawk Flight Controller",
    vendor: "Holybro",
    category: "aerospace",
    domain: "aerospace",
    protocols: ["MAVLink", "UART", "CAN", "I2C", "PWM"],
    packageType: "flight-controller",
    simulationLevel: "hil-ready",
    firmwareProfileId: "fw.pixhawk.flightstack",
    tags: ["autopilot", "px4", "uav", "hil"],
    notes: "Flight controller baseline for HIL-capable aircraft workflows.",
  },
  {
    sku: "imu-nav-grade",
    componentType: "imu-nav-grade",
    name: "Navigation-Grade IMU",
    vendor: "Generic",
    category: "aerospace",
    domain: "aerospace",
    protocols: ["CAN", "UART", "SPI"],
    packageType: "inertial-unit",
    simulationLevel: "hil-ready",
    tags: ["navigation", "avionics", "inertial"],
    notes: "Higher-fidelity inertial source for flight and guidance studies.",
  },
];

export function searchCatalog(query: string) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return marketComponentCatalog;
  return marketComponentCatalog.filter((component) =>
    [
      component.sku,
      component.componentType,
      component.name,
      component.vendor,
      component.domain,
      component.category,
      component.notes,
      component.packageType,
      component.protocols.join(" "),
      component.tags.join(" "),
    ]
      .join(" ")
      .toLowerCase()
      .includes(normalized),
  );
}

export function getCatalogComponentBySku(sku: string) {
  return marketComponentCatalog.find((component) => component.sku === sku) ?? null;
}
